import Head from 'next/head'
import Image from 'next/image'
import MyButton from '../../comps/Button'
import NavBar from '../../comps/Nav'
import MyTrack from '../../comps/TrackInfo'

import Playlist from '../../comps/Playlist'
import SbButton from '../../comps/SbButton'
import Toggle from '../../comps/Toggle'
import MyText from '../../comps/Text'
import { themes } from '../../utils/variables'
import { useTheme, useTitle, useHeader, usePar } from '../../utils/provider'
import styled from 'styled-components';
import { device } from '../../styles/mediaSizes'
import MySwitch from '../../comps/Switch'
import Slider from '../../comps/Slider'
import UserInfo from '../../comps/UserInfo'
import { useState } from 'react'



const Page = styled.div`
  display:flex;
  flex-direction: row;
  margin:0;
  justify-content: center;
  width: 100vw;
  height:95vh;
  bottom:0;

  border:2px solid red;
`;

const Dashboard = styled.div`
    background-color: ${props => props.bg};
    

    @media ${device.mobile}{
        flex-direction: column;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        height:100%;
        top:20%;

    }

    @media ${device.tablet}{
        flex-direction: row;
        justify-content: space-between;
        height:95vh;
    }

    @media ${device.desktop}{
       
    }

    border:2px solid red;
`;

const UserCont = styled.div`
    display: flex;
    align-items: center;
    flex-direction: row;
    width: 50vw;
    height: 150px;
    padding-bottom: 10px;
    margin-top: 100px;
`;

const UserImage = styled.div`
    border-radius: 50px;
    background-color: pink;
    margin: 10px 0px 10px 10px;
    height: 100px;
    width: 100px;
`;

const UserID = styled.div`
    display: flex;
    align-items: center;
    font-size: 50px; 
    color: ${props => props.color};
    height: 100px;
    width: 25vw;
    padding-left: 25px;
`;

const LeftCont = styled.div`
    display: flex;
    flex-direction: column; 
    padding-left: 50px;
`;

const SbCont = styled.div`
  display: flex;
  height: 50vh;
  width: 800px;
  justify-content: space-aroud;

  border:2px solid red;
  flex-grow: 1;
  flex-flow: column wrap;

  white-space: nowrap;
  overflow-x: scroll;
  overflow-y: hidden;

 
`;
const SliderCont = styled.div`
  display: flex;
  flex-wrap: wrap;
  width: 750px;
  justify-content: space-evenly;
  padding-left: 30px;
`;

const SpaceCont = styled.div`
display: flex;
width: 50vw;
padding-left: 20px;

justify-content: space-between;
border:2px solid red;
`;

const TracksCont = styled.div`
    height:40%;
    border:2px solid red;
    /* position: absolute; */
    /* bottom:0;
    left:10px; */
    align-self: center;
    width:50vw;

    flex-grow: 1
    
`;

const RegCont = styled.div`
  padding-left: 30px;
  border:2px solid red;
  
`;

const Divider = styled.div`
    background-color: ${props => props.color};
    width:90%;
    height:1px;
`;


export default function User() {

    //this will be replaced with data from db

    const { theme } = useTheme();
    const [selected, setSelected] = useState(null);
    const { titleSize } = useTitle();
    const { headerSize } = useHeader();
    const { parSize } = usePar();

    const [addedRecent, setAddedRecent] = useState(true)

    return (
        <>
            <Head>
                <title>botBot</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="#" />
            </Head>
            <Page>
                <LeftCont>

                
                <UserCont>
                    <UserImage/>
                    <UserID
                     color={themes[theme].text} 
                    >User 123</UserID>

                </UserCont>

                <Dashboard
                    bg={themes[theme].contrast}>

                    {/* <UserInfo /> */}
                    <MyText
                        weight={500}
                        lineHeight='0'
                        text={`Your playlists`}
                        size={`${titleSize}px`}
                    />

                    <SbCont>
                        {/* map this out: */}
                        <Playlist
                            cover='/playlistLiked.png'
                            onClick={() => setSelected('liked')}
                            bg={selected === 'liked' || null ? themes[theme].accent : themes[theme].playBg}
                            color={selected === 'liked' || themes[theme].white ? themes[theme].text : themes[theme].accent}
                            text='liked'
                        />
                        <Playlist
                            cover='/playlistRap.png'
                            onClick={() => setSelected('rap')}
                            bg={selected === 'rap' ? themes[theme].accent : themes[theme].playBg}
                            color={selected === 'rap' ? themes[theme].white : themes[theme].accent}
                            text='rap'
                        />
                        <Playlist
                            cover='/playlistPop.png'
                            onClick={() => setSelected('pop')}
                            bg={selected === 'pop' ? themes[theme].accent : themes[theme].playBg}
                            color={selected === 'pop' ? themes[theme].white : themes[theme].accent}
                            text='pop'
                        />
                        <Playlist
                            cover='/playlistIndie.png'
                            onClick={() => setSelected('indie')}
                            bg={selected === 'indie' ? themes[theme].accent : themes[theme].playBg}
                            color={selected === 'indie' ? themes[theme].white : themes[theme].accent}
                            text='indie'
                        />

                        <Playlist
                            cover='/playlistLiked.png'
                            onClick={() => setSelected('liked')}
                            bg={selected === 'liked' || null ? themes[theme].accent : themes[theme].playBg}
                            color={selected === 'liked' || themes[theme].white ? themes[theme].text : themes[theme].accent}
                            text='liked'
                        />
                        <Playlist
                            cover='/playlistRap.png'
                            onClick={() => setSelected('rap')}
                            bg={selected === 'rap' ? themes[theme].accent : themes[theme].playBg}
                            color={selected === 'rap' ? themes[theme].white : themes[theme].accent}
                            text='rap'
                        />
                        <Playlist
                            cover='/playlistPop.png'
                            onClick={() => setSelected('pop')}
                            bg={selected === 'pop' ? themes[theme].accent : themes[theme].playBg}
                            color={selected === 'pop' ? themes[theme].white : themes[theme].accent}
                            text='pop'
                        />
                        <Playlist
                            cover='/playlistIndie.png'
                            onClick={() => setSelected('indie')}
                            bg={selected === 'indie' ? themes[theme].accent : themes[theme].playBg}
                            color={selected === 'indie' ? themes[theme].white : themes[theme].accent}
                            text='indie'
                        />

                    </SbCont>
                </Dashboard>
                </LeftCont>

                <TracksCont>
                        <SpaceCont>
                            <MyText
                                text={selected === null ? 'liked' : selected}
                                size={`${headerSize}px`}
                            />
                            <MyButton
                                onClick={() => setAddedRecent(!addedRecent)}
                                text={addedRecent ? 'See oldest ' : 'See newest'}
                            />

                        </SpaceCont>

                        <Divider
                            color={themes[theme].text} />
                        <br></br>

                        <RegCont>
                            <MyTrack />
                            <MyTrack />
                            <MyTrack />
                        </RegCont>

                    </TracksCont>
                    

            </Page>
        
        </>
    )
}
