import Head from 'next/head'
import Image from 'next/image'
import MyButton from '../comps/Button'

export default function Home() {
  return (
    <div className={'page'}>
      <Head>
        <title>botBot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="#" />
      </Head>

      <MyButton />
      
      
    </div>
  )
}
