import Head from 'next/head'
import Image from 'next/image'
import MyButton from '../comps/Button'
import NavBar from '../comps/Nav'
import MyTrack from '../comps/TrackInfo'

import Playlist from '../comps/Playlist'
import SbButton from '../comps/SbButton'
import Toggle from '../comps/Toggle'
import MyText from '../comps/Text'
import { themes } from '../utils/variables'
import { useTheme, useTitle, useHeader, usePar, useGenre } from "../utils/provider";import styled from 'styled-components';
import { device } from '../styles/mediaSizes'
import MySwitch from '../comps/Switch'
import Slider from '../comps/Slider'
import Divider from '../comps/Divider'
import ThemeToggle from '../comps/ThemeToggle'
import { useState } from 'react'



const Dashboard = styled.div`
    background-color: ${props => props.bg};
    position: absolute;
    top:0;
    right:0;
    height:99%;
    padding:10px;
    width: 75%;
    max-width: 950px;

    @media ${device.mobile}{

    }

    @media ${device.tablet}{
    }

    @media ${device.desktop}{
       
    }
`;


const Cont = styled.div`
  display: flex;
  flex-direction: row;
`;

const HalfCont = styled.div`
  flex:1;
`



export default function Settings() {

  const { theme, setTheme } = useTheme();
  const [themeCol, setThemeCol] = useState(theme);
  const {titleSize, setTitleSize} = useTitle();
  const {headerSize, setHeaderSize} = useHeader();
  const {parSize, setParSize} = usePar();
  
  let title = titleSize;
  let header = headerSize;
  let par = parSize;

  function increaseFont(){
    setTitleSize(title+=2)
    setHeaderSize(header+=2)
    setParSize(par+=2)
  }
  function decreaseFont(){
    setTitleSize(title-=2)
    setHeaderSize(header-=2)
    setParSize(parent-=2)
  }

  //filtering
  const {genre, setGenre} = useGenre();


  return (
    <>
      <Head>
        <title>botBot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="#" />
      </Head>
      <NavBar />

      <Dashboard
        bg={themes[theme].contrast}>
        <MyText
          text={`Settings`}
          size={`${titleSize}px`} />

        <Cont>
          <HalfCont>
            <MyText
              text='Themes'
              size={`${headerSize}px`}
            />

            <MyText
              text='Font size'
              size={`${headerSize}px`}
            />

          </HalfCont>
          <HalfCont>
            <ThemeToggle 
            onClick={()=> setTheme('dark')}
            mode='Dark Mode' 
            theme1={themes.dark.mid}
            theme2={themes.dark.accent1}
            display={'circle'}
            innerCol={themes[theme].focus}
            outerCol={themes[theme].focus}
            />  
            <ThemeToggle 
            onClick={()=> setTheme('light')}
            mode='Light Mode' 
            theme1={themes.light.mid}
            theme2={themes.light.accent1}
            display={'circle'}
            innerCol={themes[theme].focus}
            outerCol={themes[theme].focus}
            />  
            <ThemeToggle
            onClick={()=> setTheme('retro')} 
            mode='Retro' 
            theme1={themes.retro.mid}
            theme2={themes.retro.accent1}
            display={'circle'}
            innerCol={themes[theme].focus}
            outerCol={themes[theme].focus}
            />  
            <ThemeToggle 
            onClick={()=> setTheme('funky')}
            mode='Funk' 
            theme1={themes.funky.mid}
            theme2={themes.funky.accent1}
            display={'circle'}
            innerCol={themes[theme].focus}
            outerCol={themes[theme].focus}
            />  
            <Toggle 
              increase={increaseFont}
              decrease={decreaseFont}
            />


          </HalfCont>
        </Cont>
      </Dashboard>
    </>
  )
}
